title: "YK Portfolio"
url: "https://ykportfolio.github.io/"
baseurl: "" # якщо сайт у корені репозиторію; якщо в папці — вкажи /назва-репозиторію

plugins:
  - jekyll-datapage-generator
  - jekyll-sitemap
  - jekyll-minifier

datapage_gen:
  - data: projects
    template: project
    name: name
    dir: "gallery"
    extension: "html"
    lang: en

  - data: projects
    template: project
    name: name
    dir: "ua/gallery"
    extension: "html"
    lang: ua

jekyll-minifier:
  compress_html: true
  compress_css: true
  compress_javascript: true
  remove_comments: true
  remove_intertag_spaces: true
  remove_multi_spaces: true
  remove_quotes: true
  simple_doctype: true

require:
  - base64
  - csv

sass:
  style: compressed

permalink: pretty

exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .sass-cache
  - .jekyll-cache
  - Rakefile
  - .DS_Store
  - .bundle
  - README.md
  - package.json
  - package-lock.json